"""empty message

Revision ID: bc661c6d0a8b
Revises: 482640b56423
Create Date: 2019-12-27 19:10:57.190717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc661c6d0a8b'
down_revision = '482640b56423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone_number', table_name='order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone_number', 'order', ['phone_number'], unique=True)
    # ### end Alembic commands ###
